name: build 

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  GO_VERSION: 1.23

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: image
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: splat-bot
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile      
