name: test
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  GO_VERSION: '1.23'
    
jobs:
  test:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Test with the Go CLI
        continue-on-error: true
        run: "./hack/unit.sh"
